export default {
    products: [{
        _id: 1,
        name: "Pink Polka Dot Disposable Paper Cups - Pack of 10 - 200ml",
        category: "Paper Cups",
        image: "/images/j1.jpg",
        price: 189,
        countInStock: 30,
        rating: 4.5,
        numReviews: 10,
        description: 'good product',
    },
    {
        _id: 2,
        name: "White Paper Cups - 100ml (Pack of 100 Pcs)",
        category: "Paper Cups",
        image: "/images/j2.jpg",
        price: 125,
        countInStock: 50,
        rating: 4,
        numReviews: 10,
        description: 'good product',
    },
    {
        _id: 3,
        name: "Zig Zag Printed Disposable Party Paper Cups for Hot & Cold Beverages - 200ml (100 Pieces)",
        category: "Paper Cups",
        image: "/images/j3.jpg",
        price: 240,
        countInStock: 15,
        rating: 4.6,
        numReviews: 72,
        description: 'good product',
    },
    {
        _id: 4,
        name: "HOME REPUBLIC- Pack of 20 Transparent Square Cups/Sample Shot Glasses Plastic Dessert Cups",
        category: "Paper Cups",
        image: "/images/j4.jpg",
        price: 370,
        countInStock: 10,
        rating: 3,
        numReviews: 27,
        description: 'good product',
    },
    {
        _id: 5,
        name: "Reusable Plastic Drinking Glass (or) Juice Tumbler Assorted Colours 300 ml (Set of 24)",
        category: "Plastic Cups",
        image: "/images/j5.jpg",
        price: 399,
        countInStock: 10,
        rating: 3.7,
        numReviews: 32,
        description: 'good product',
    },

    {
        _id: 6,
        name: "Plastic Unbreakable Drinking Glass Set - 6 PCS(Transparent)",
        category: "Plastic Cups",
        image: "/images/j6.jpg",
        price: 299,
        countInStock: 25,
        rating: 4.6,
        numReviews: 3,
        description: 'good product',
    },

    {
        _id: 7,
        name: "Water Drinking Plastic Cups Set of 12, Unbreakable, Clear Juice Cup for Home (Green) , 250 ml",
        category: "Plastic Cups",
        image: "/images/j7.jpg",
        price: 492,
        countInStock: 20,
        rating: 4.2,
        numReviews: 21,
        description: 'good product',
    },
    {
        _id: 8,
        name: "Water Drinking Plastic Cups Set of 12, Unbreakable, Clear Juice Cup for Home (Purple) , 250 ml",
        category: "Plastic Cups",
        image: "/images/j8.jpg",
        price: 422,
        countInStock: 15,
        rating: 4.6,
        numReviews: 23,
        description: 'good product',
    },
    {
        _id: 9,
        name: "Pack of 150 : 8 Oz White Disposable Coffee Foam Cups Hot and Cold Drink Cup (Pack of 150)",
        category: "Foam Cups",
        image: "/images/j9.jpg",
        price: 2653,
        countInStock: 5,
        rating: 4.6,
        numReviews: 185,
        description: 'good product',
    },
    ]
}