import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Joyelle',
      email: 'joyfleurndikumana@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'Elvis',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
    products: [{
        _id: 1,
        name: "Pink Polka Dot Disposable Paper Cups - Pack of 10 - 200ml",
        category: "Paper Cups",
        image: "/images/j1.jpg",
        price: 189,
        countInStock: 30,
        rating: 4.5,
        numReviews: 10,
        description: 'Disposable Party Cups- 100 cups, Sturdy and waterproof, Stylish and leakproof, PolkaDot design cups, easy to hold and Durable',
    },
    {
        _id: 2,
        name: "White Paper Cups - 100ml (Pack of 100 Pcs)",
        category: "Paper Cups",
        image: "/images/j2.jpg",
        price: 125,
        countInStock: 50,
        rating: 4,
        numReviews: 10,
        description: 'Good product, easy to hold and durable.',
    },
    {
        _id: 3,
        name: "Zig Zag Printed Disposable Party Paper Cups for Hot & Cold Beverages - 200ml (100 Pieces)",
        category: "Paper Cups",
        image: "/images/j3.jpg",
        price: 240,
        countInStock: 15,
        rating: 4.6,
        numReviews: 72,
        description: 'Disposable cups, stylish, easy to hold and durable',
    },
    {
        _id: 4,
        name: "HOME REPUBLIC- Pack of 20 Transparent Square Cups/Sample Shot Glasses Plastic Dessert Cups",
        category: "Paper Cups",
        image: "/images/j4.jpg",
        price: 370,
        countInStock: 10,
        rating: 3,
        numReviews: 27,
        description: 'good product',
    },
    {
        _id: 5,
        name: "Reusable Plastic Drinking Glass (or) Juice Tumbler Assorted Colours 300 ml (Set of 24)",
        category: "Plastic Cups",
        image: "/images/j5.jpg",
        price: 399,
        countInStock: 10,
        rating: 3.7,
        numReviews: 32,
        description: 'Transperant Colouful ABS unbreakable Glasses. Made of Food Grade Plastic Material ABS / BPA Free Note : Image color may vary from the actual product due to Lightning effect and editing',
    },

    {
        _id: 6,
        name: "Plastic Unbreakable Drinking Glass Set - 6 PCS(Transparent)",
        category: "Plastic Cups",
        image: "/images/j6.jpg",
        price: 299,
        countInStock: 25,
        rating: 4.6,
        numReviews: 3,
        description: 'good product',
    },

    {
        _id: 7,
        name: "Water Drinking Plastic Cups Set of 12, Unbreakable, Clear Juice Cup for Home (Green) , 250 ml",
        category: "Plastic Cups",
        image: "/images/j7.jpg",
        price: 492,
        countInStock: 20,
        rating: 4.2,
        numReviews: 21,
        description: 'good product',
    },
    {
        _id: 8,
        name: "Water Drinking Plastic Cups Set of 12, Unbreakable, Clear Juice Cup for Home (Purple) , 250 ml",
        category: "Plastic Cups",
        image: "/images/j8.jpg",
        price: 422,
        countInStock: 15,
        rating: 4.6,
        numReviews: 23,
        description: 'good product',
    },
    {
        _id: 9,
        name: "Pack of 150 : 8 Oz White Disposable Coffee Foam Cups Hot and Cold Drink Cup (Pack of 150)",
        category: "Foam Cups",
        image: "/images/j9.jpg",
        price: 2653,
        countInStock: 5,
        rating: 4.6,
        numReviews: 185,
        description: 'good product',
    },
    {
        _id: 10,
        name: "TRUENOW VENTURES PRIVATE LIMITED Glass Tea and Coffee Cup (Clear, 140 ml) 6 Pieces",
        category: "Glass Cups",
        image: "/images/j10.jpg",
        price: 449,
        countInStock: 7,
        rating: 4.1,
        numReviews: 279,
        description: 'This transparent tea cup is made of lead-free high-borosilicate heat-resistant glass, making your hot or cold drink ideal for long periods of time thanks to its durability, high quality and unique ability temperature.',
    },
    {
        _id: 11,
        name: "CYNFLEES Glass Tea and Coffee Cup - Set of 2 , Clear, 410ml (Lemon Tea Cup, 2)",
        category: "Glass Cups",
        image: "/images/j11.jpg",
        price: 449,
        countInStock: 12,
        rating: 3.2,
        numReviews: 7,
        description: 'Strong,& Durable Microwave & Dishwasher safe Lead-free Food Grade Glaze',
    },
    {
        _id: 12,
        name: "DITYA Enterprise Tea/Coffee Cups, Stainless Steel Apple Tea & Coffee Cups, (Set of 6, 100 ml)",
        category: "Stainless Steel Cups",
        image: "/images/j12.jpg",
        price: 554,
        countInStock: 13,
        rating: 3.8,
        numReviews: 12,
        description: "Stainless Steel Double Wall Tea Mug Set is a unique product. It's time for you to say goodbye to your old coffee mugs, that fade or discolor over time & Bring home this swanky new set of two, that redefines your sense of style. This exotic silver shining mug set has a capacity of 150ml each. Made from 100% Stainless Steel making them highly durable and resistance to corrosion, You will find these mugs only in 7 Stars or out of the Big Luxurious Hotel, and Drinking Tea or coffee in them make you feel like the King Size. We make you assure your while drinking morning Tea/ coffee in these mugs make you morning and evening Vibrant.",
    },
    {
        _id: 13,
        name: "SUMEET Stainless Steel Coffee Mug - 4 Pieces, Silver, 210 ml",
        category: "Stainless Steel Cups",
        image: "/images/j13.jpg",
        price: 831,
        countInStock: 31,
        rating: 3.7,
        numReviews: 63,
        description: "This Stainless Steel double wall tea Mug set of 4 from the house of Sumeet is all about serving your favorite tea / Coffee at its beautiful best. It is made of high quality stainless steel which makes it highly durable in nature and adds a charming touch to every kind of contemporary space and setting. It is easy to wash and its design and material keeps the liquid kept in it warm for long. The exotic silver shining mug set has a capacity of 160ml Each. They are very useful, long lasting and very easy to maintain.",
    },
    {
        _id: 14,
        name: "SANWALSA (350 ml ,Black, 12 Oz)- Pack of 25-Piece Paper Disposable Ripple Cup Ecofriendly, Safe & Hygienic for Juice,Coffee,Tea ,Home,Office ,Party & Wedding Events",
        category: "Paper Cups",
        image: "/images/j14.jpg",
        price: 289,
        countInStock: 112,
        rating: 3.9,
        numReviews: 6,
        description: "Ripple paper cups are essentially double-wall hot cups finished with a layer of Kraft 'ripple' paper on the outside. This rippled outer layer prevents the hot contents from burning the hands and aids heat retention of the product within. Rippled Cups are becoming the popular stand-out disposable cup for coffee shops, caterers, homes, takeaways, and offices all over the country.",
    },
    {
        _id: 15,
        name: "Rks imporium Ceramic 6 Cup of Set Tea/Coffee Cups",
        category: "Ceramic Cups",
        image: "/images/j15.jpg",
        price: 339,
        countInStock: 112,
        rating: 5,
        numReviews: 16,
        description: "Rks imporium Ceramic 6 Cup of Set. Buy and enjoy your drink",
    },
    {
        _id: 16,
        name: "The Earth Store Stylish Ceramic Handcrafted Black Pari Dot Printed Microwave Safe Tea Cup/Coffee Cup Set Ideal Best Gift for Friends, Family, Home, Office use, Kitchen Cup Set (Set of 6, 130 ML)",
        category: "Ceramic Cups",
        image: "/images/j16.jpg",
        price: 349,
        countInStock: 24,
        rating: 4.3,
        numReviews: 161,
        description: "Enhance your tea or coffee experience with these unique styled and good quality tea cups with your family or friends. Featuring an attractive and stylish design coffee cups from the house of The Earth Store. These tea/coffee cups are best for serving coffee, Hot Chocolate, Green Tea, Black Tea, Green Tea, Masala Chai, Kawa, and other hot beverages. These coffee cups will be a wonderful addition to your home or office",
    },
    {
        _id: 17,
        name: "The Earth Store Stylish Ceramic Handcrafted Black Pari Dot Printed Microwave Safe Tea Cup/Coffee Cup Set Ideal Best Gift for Friends, Family, Home, Office use, Kitchen Cup Set (Set of 6, 130 ML)",
        category: "Ceramic Cups",
        image: "/images/j17.jpg",
        price: 474,
        countInStock: 12,
        rating: 3.8,
        numReviews: 165,
        description: "These tea/coffee cups are best for serving coffee, Hot Chocolate, Green Tea, Black Tea, Green Tea, Masala Chai, Kawa and other hot beverages. These coffee mugs will be a wonderful addition to your home or office. These handcrafted crockery items are crafted by the best artisans in the pottery of Khurja, Uttar Pradesh India, keeping in mind to present you with the unique design for your kitchen and dining.",
    },
    {
        _id: 18,
        name: "Zaitra Set of 25 (25 Cup + 25 lid) Disposable Paper Cup for Coffee/Tea Drinks, 300 ml Cup with Lid",
        category: "Paper Cups",
        image: "/images/j18.jpg",
        price: 399,
        countInStock: 27,
        rating: 4.3,
        numReviews: 3,
        description: "Use for hot drinks or cold drinks sip a cup of hot coffee in the morning or a cold glass of juice when you come home or go in the office. Hence you chose a hot drink or cold beverage our disposable cup makes your life simple.",
    },
    {
        _id: 19,
        name: "The Earth Store Stylish Ceramic Handcrafted Black Pari Dot Printed Microwave Safe Tea Cup/Coffee Cup Set Ideal Best Gift for Friends, Family, Home, Office use, Kitchen Cup Set (Set of 6, 130 ML)",
        category: "Ceramic Cups",
        image: "/images/j19.jpg",
        price: 349,
        countInStock: 39,
        rating: 4,
        numReviews: 11,
        description: "high quality ceramic material, microwave & dishwasher safe, permanent and fade-proof printing, Easy to clean, Strain free",
    },
    {
        _id: 20,
        name: "Dharam Paul Traders Stainless Steel Tea Cup - 6 Pieces, Metallic, 150 ml",
        category: "Stainless Steel Cups",
        image: "/images/j20.jpg",
        price: 489,
        countInStock: 63,
        rating: 4.1,
        numReviews: 407,
        description: "NEW BELLY DESIGN: These steel tea cups come in a nice and new Narrow Belly shaped design which gives a fresh look to your cups for tea. \n STRONG MATERIAL: These cups for tea are made up from High Quality Stainless Steel, which is known for its durability and strength. \n NON BREAKABLE: As the cups are made from stainless steel, these will not break even after getting dropped any number of times.",
    },
    ]
};
export default data;